### ISSUE TITLE
`mintdump dump` should stop chain, maybe with `--stop`

### ISSUE THREAD

**Issue by zramsay** [eris-ltd/mint-client#18]
- [ ] `--stop`
- [ ] `--copy`

if chain is running & I run `mintdump dump` : panic: Paniced on a Crisis: resource temporarily unavailable

is it possible to `dump` while chain is running? if so, then let's do that. (not sure how...). 

or is the whole point of `mintdump dump` that you've stopped a chain to save state for later (i.e., #15) . if so, then cmd should prompt user to stop chain to add `--stop` to avoid throwing the panic error. Thoughts?

**Comment by ebuchman** [comment]
ya good question. currently the node has to be stopped because only one process can access the db at a time. `--stop` is a good compromise. the other option is to make `dump` an rpc endpoint within tendermint itself, and then the tool just needs to hit that endpoint. not sure if that's a good idea yet tho, ill bring up with jae. in meantime use `--stop`

**Comment by ebuchman** [comment]
actually there's a third option which is to make a copy of the whole database directory, delete the LOCK file, and then have mintdump use the copied dir. but thats kind of messy. though its also a reasonable compromise if the chains not too big. maybe we can have a `--copy` flag too. so you either give `--stop` or `--copy` to get the job done while chain is running (make sure --copy cleans up after itself (ie removes the copied dir) when done!)

**Comment by zramsay** [comment]
waiting on updates to tmint?

**Comment by zramsay** [comment]
obsolete for the time being
